 const links = [
{ 
    url: './Urgenthirarky.html', 
    text: 'urgent hierarky', 
    color: '#66DE97', 
    description: 'Tool for generating CSS gradient colors.' 
},
{ url: 'https://www.google.com', text: 'Google', color: '#4285F4', description: 'Search engine for the web.' },
{ url: 'https://www.facebook.com', text: 'Facebook', color: '#1877F2', description: 'Social media platform.' },
{ url: 'https://www.twitter.com', text: 'Twitter', color: '#1DA1F2', description: 'Microblogging and social networking service.' },
{ url: 'https://www.linkedin.com', text: 'LinkedIn', color: '#0077B5', description: 'Professional networking platform.' },
{ url: 'https://www.github.com', text: 'GitHub', color: '#181717', description: 'Code hosting platform for version control and collaboration.' },
{ url: 'https://www.instagram.com', text: 'Instagram', color: '#C13584', description: 'Photo and video sharing social network.' },
{ url: 'https://www.youtube.com', text: 'YouTube', color: '#FF0000', description: 'Video-sharing platform.' },
{ url: 'https://www.whatsapp.com', text: 'WhatsApp', color: '#25D366', description: 'Messaging application for smartphones.' },
{ url: 'https://www.pinterest.com', text: 'Pinterest', color: '#BD081C', description: 'Visual discovery engine for finding ideas.' },
{ url: 'https://www.zoom.us', text: 'Zoom', color: '#2D8CFF', description: 'Video conferencing platform.' },
{ url: 'https://chat.openai.com', text: 'ChatGPT', color: '#10A37F', description: 'AI-based conversational assistant.' },
{ url: 'https://mail.google.com', text: 'Gmail', color: '#D93025', description: 'Email service from Google.' },
{ url: 'https://www.google.com/drive/', text: 'Google Drive', color: '#34A853', description: 'Cloud storage service by Google.' },
{ url: 'https://www.google.com/calendar', text: 'Google Calendar', color: '#4285F4', description: 'Calendar service to manage events and schedules.' },
{ url: 'https://www.google.com/maps', text: 'Google Maps', color: '#34A853', description: 'Map and navigation service.' },
{ url: 'https://www.google.com/photos', text: 'Google Photos', color: '#34A853', description: 'Photo storage and sharing service.' },
{ url: 'https://news.google.com', text: 'Google News', color: '#4285F4', description: 'Curated news articles and headlines.' },
{ url: 'https://translate.google.com', text: 'Google Translate', color: '#4285F4', description: 'Language translation service by Google.' },
{ url: 'https://docs.google.com', text: 'Google Docs', color: '#4285F4', description: 'Cloud-based document editing tool.' },
{ url: 'https://sheets.google.com', text: 'Google Sheets', color: '#34A853', description: 'Spreadsheet application by Google.' },
{ url: 'https://slides.google.com', text: 'Google Slides', color: '#FBBC05', description: 'Presentation software by Google.' },
{ url: 'https://meet.google.com', text: 'Google Meet', color: '#34A853', description: 'Video conferencing service.' },
{ url: 'https://play.google.com', text: 'Google Play', color: '#4285F4', description: 'Google’s digital distribution service.' },
{ url: 'https://books.google.com', text: 'Google Books', color: '#4285F4', description: 'Search and read digital books online.' },

  // Microsoft services
{ url: 'https://www.microsoft.com', text: 'Microsoft', color: '#F25022', description: 'Technology company specializing in software and hardware.' },
{ url: 'https://www.office.com', text: 'Microsoft Office', color: '#D83B01', description: 'Office productivity suite.' },
{ url: 'https://outlook.live.com', text: 'Outlook', color: '#0078D4', description: 'Email and calendar service by Microsoft.' },
{ url: 'https://www.onedrive.com', text: 'OneDrive', color: '#0078D4', description: 'Cloud storage service by Microsoft.' },
{ url: 'https://www.skype.com', text: 'Skype', color: '#00AFF0', description: 'Video and voice calling service.' },
{ url: 'https://www.teams.microsoft.com', text: 'Microsoft Teams', color: '#6264A7', description: 'Collaboration and communication platform.' },
{ url: 'https://www.microsoft.com/en-us/edge', text: 'Microsoft Edge', color: '#0078D4', description: 'Web browser developed by Microsoft.' },
{ url: 'https://www.bing.com', text: 'Bing', color: '#008373', description: 'Search engine from Microsoft.' },
{ url: 'https://www.xbox.com', text: 'Xbox', color: '#107C10', description: 'Gaming console brand by Microsoft.' },
{ url: 'https://www.azure.microsoft.com', text: 'Microsoft Azure', color: '#0078D4', description: 'Cloud computing services platform.' },
{ url: 'https://www.microsoft.com/en-us/windows', text: 'Windows', color: '#0078D4', description: 'Operating system developed by Microsoft.' },
{ url: 'https://docs.microsoft.com', text: 'Microsoft Docs', color: '#5A5A5A', description: 'Technical documentation for Microsoft products.' },
{ url: 'https://forms.office.com', text: 'Microsoft Forms', color: '#0078D4', description: 'Survey and quiz creation tool by Microsoft.' },
{ url: 'https://www.microsoft.com/en-us/learn', text: 'Microsoft Learn', color: '#6264A7', description: 'Learning platform offering training materials for Microsoft products.' },

  // Collection
{ url: 'https://ukin-ukpppg.bppp.kemdikbud.go.id/', text: 'UKPPPG Kemdikbud', color: '#005BBB', description: 'Educational portal by the Ministry of Education and Culture.' },
{ url: 'https://ninite.com/', text: 'Ninite', color: '#398DEE', description: 'Software installation automation service.' },
{ url: 'https://akupintar.id/info-pintar/-/blogs/magnet-pengertian-sifat-jenis-dan-bentuk-magnet', text: 'Aku Pintar', color: '#4CAF50', description: 'Educational resource about magnetism.' },
{ url: 'https://kusonime.com/spy-kyoushitsu-batch-subtitle-indonesia/', text: 'Kusonime - Spy Kyoushitsu', color: '#FF4500', description: 'Download anime with Indonesian subtitles.' },
{ url: 'https://aicomicfactory.com/playground', text: 'AI Comic Factory', color: '#F39C12', description: 'AI-generated comic creation tool.' },
{ url: 'https://www.educaplay.com/', text: 'Educaplay', color: '#FFC107', description: 'Interactive educational content creation platform.' },
{ url: 'https://www.dora.run/ai', text: 'Dora AI', color: '#8E44AD', description: 'AI-powered productivity tools.' },
{ url: 'https://www.studyfetch.com/id/platform?justLoggedIn=true', text: 'StudyFetch', color: '#27AE60', description: 'Platform for academic resources.' },
{ url: 'https://id.elsevier.com/', text: 'Elsevier', color: '#1E8449', description: 'Global provider of scientific information.' },
{ url: 'https://www.figma.com/', text: 'Figma', color: '#0ACF83', description: 'Collaborative interface design tool.' },
{ url: 'https://app.formulabot.com/', text: 'FormulaBot', color: '#FF4500', description: 'Tool to generate Excel formulas using AI.' },
{ url: 'https://zapier.com', text: 'Zapier', color: '#FF4A00', description: 'Automates workflows between apps to save time.' },
{ url: 'https://www.make.com', text: 'Make', color: '#33A1FD', description: 'Visual platform for creating automated workflows.' },
{ url: 'https://www.bardeen.ai', text: 'Bardeen', color: '#7350C1', description: 'AI automation tool that helps with repetitive tasks.' },
{ url: 'https://bard.google.com', text: 'Google Bard', color: '#4285F4', description: 'Google’s experimental conversational AI.' },
{ url: 'https://gemini.com', text: 'Gemini', color: '#00DC82', description: 'Cryptocurrency exchange and custodian.' },
{ url: 'https://copilot.microsoft.com', text: 'Copilot X', color: '#0078D4', description: 'Microsoft’s AI-powered tool for enhanced productivity.' },
{ url: 'https://www.askcodi.com', text: 'AskCodi', color: '#4CAF50', description: 'AI tool for developers to generate code snippets.' },
{ url: 'https://aws.amazon.com', text: 'AWS', color: '#FF9900', description: 'Amazon Web Services - Cloud computing platform.' },
{ url: 'https://aws.amazon.com/codewhisperer', text: 'Code Whisperer', color: '#232F3E', description: 'Amazon’s AI coding companion.' },
{ url: 'https://www.syllaby.io', text: 'Syllaby', color: '#FF6F61', description: 'AI content creation for course builders.' },
{ url: 'https://www.midjourney.com', text: 'MidJourney', color: '#5961F9', description: 'AI tool for creating high-quality images.' },
{ url: 'https://www.cohesive.so', text: 'Cohesive', color: '#29B6F6', description: 'AI writing assistant for enhanced productivity.' },
{ url: 'https://www.synthesia.io', text: 'Synthesia', color: '#FC5867', description: 'AI video generation platform using avatars.' },
{ url: 'https://www.adobe.com/sensei/generative-ai/firefly.html', text: 'Adobe Firefly', color: '#F75000', description: 'Generative AI tool for creating art and designs.' },
{ url: 'https://designer.microsoft.com', text: 'Microsoft Designer', color: '#68217A', description: 'Microsoft’s AI-powered design tool for quick creation.' },
{ url: 'https://www.tome.app', text: 'Tome', color: '#FF5A5F', description: 'AI-powered storytelling platform for presentations.' },
{ url: 'https://www.decktopus.com', text: 'Decktopus', color: '#346DF1', description: 'AI-powered presentation tool for generating slides.' },
{ url: 'https://www.gamma.app', text: 'Gamma', color: '#8E44AD', description: 'AI-powered platform for creating engaging documents.' },
{ url: 'https://www.notion.so/product/ai', text: 'Notion AI', color: '#000000', description: 'AI-enhanced productivity for note-taking and documents.' },
{ url: 'https://www.taskade.com', text: 'Taskade', color: '#FF4C4C', description: 'Collaboration and task management tool with AI.' },
{ url: 'https://meetgeek.ai', text: 'MeetGeek', color: '#FF8000', description: 'AI-powered meeting transcription and summarization.' },
{ url: 'https://www.runwayml.com', text: 'Runway', color: '#00ADEF', description: 'AI creative suite for video, image, and design editing.' },
{ url: 'https://pictory.ai', text: 'Pictory', color: '#FBC02D', description: 'AI video creation from scripts and blogs.' },
{ url: 'https://www.descript.com', text: 'Descript', color: '#3E7CFF', description: 'AI-powered tool for audio and video editing.' },
{ url: 'https://www.10web.io', text: '10Web', color: '#2F2E41', description: 'AI website builder and optimization platform.' },
{ url: 'https://durable.co', text: 'Durable', color: '#FF6161', description: 'AI-powered tool to create websites instantly.' },
{ url: 'https://imagica.ai', text: 'Imagica', color: '#F5A623', description: 'AI platform for transforming images into designs.' },
{ url: 'https://www.klingai.com/', text: 'Klingai', color: '#00796B', description: 'AI tool for building interactive voice applications.' },
{ url: 'https://free3d.com/3d-models/characters', text: 'Free3D Characters', color: '#F15A24', description: 'Platform to download free 3D models for characters.' },
{ url: 'https://soundraw.io/edit_music', text: 'Soundraw', color: '#FF4081', description: 'AI music generator for creators.' },
{ url: 'https://mixkit.co/', text: 'Mixkit', color: '#00A88B', description: 'Free assets for videos, including music and templates.' },
{ url: 'https://getcartwheel.com/gallery', text: 'Cartwheel Gallery', color: '#E91E63', description: 'A gallery for video and motion design assets.' },
{ url: 'https://vidyo.ai/', text: 'Vidyo', color: '#FF5A60', description: 'AI-powered platform for short video creation.' },
{ url: 'https://www.freeadcopy.com/dashboard/templates', text: 'FreeAdCopy Templates', color: '#5C6BC0', description: 'Free AI-generated advertising copy templates.' },
{ url: 'https://www.morphic.sh/', text: 'Morphic', color: '#212121', description: 'AI tool for generating diverse website templates.' },
{ url: 'https://www.data-to-viz.com/', text: 'Data to Viz', color: '#7C4DFF', description: 'Guides for creating data visualizations.' },
{ url: 'https://creatorset.com/', text: 'CreatorSet', color: '#9C27B0', description: 'Assets for creators, including animations and templates.' },
{ url: 'https://jttr.io/', text: 'Jttr', color: '#2D88FF', description: 'AI for generating personalized content feeds.' },
{ url: 'https://meettrenda.com/', text: 'Meet Trenda', color: '#26C6DA', description: 'AI social media manager and content curator.' },
{ url: 'https://elevenlabs.io/', text: 'ElevenLabs', color: '#FF5722', description: 'AI voice generator and text-to-speech platform.' },
{ url: 'https://quickdraw.withgoogle.com/', text: 'Quick, Draw!', color: '#FFD600', description: 'AI game where you draw and the AI guesses.' },
{ url: 'https://tree.fm/', text: 'tree.fm', color: '#388E3C', description: 'Tune into calming sounds of forests from around the world.' },
{ url: 'https://fontstruct.com/', text: 'FontStruct', color: '#6200EA', description: 'Platform to build and download custom fonts.' },
{ url: 'https://www.autodraw.com/', text: 'AutoDraw', color: '#03A9F4', description: 'Google’s AI tool for quick drawing assistance.' },
{ url: 'https://thispersondoesnotexist.com/', text: 'This Person Does Not Exist', color: '#616161', description: 'AI-generated images of non-existent people.' },
{ url: 'https://ai-music-generator.ai/', text: 'AI Music Generator', color: '#1E88E5', description: 'AI music generator for custom tracks.' },
{ url: 'https://www.oldgamesdownload.com/', text: 'Old Games Download', color: '#8BC34A', description: 'Download abandonware and classic games.' },
{ url: 'https://www.unscreen.com/', text: 'Unscreen', color: '#00BCD4', description: 'AI tool to remove video backgrounds instantly.' },
{ url: 'https://superdesigner.co/', text: 'Super Designer', color: '#FF9800', description: 'Tool for creating beautiful designs quickly.' },
{ url: 'https://calligraphr.com/', text: 'Calligraphr', color: '#EF5350', description: 'Create custom fonts from your handwriting.' },
{ url: 'https://jitter.video/', text: 'Jitter', color: '#FFAB40', description: 'Simple motion design tool for creating animations.' },
{ url: 'https://www.canva.com', text: 'Canva', color: '#00C4CC', description: 'Design tool for creating graphics, presentations, posters, and more.' },
{ url: 'https://www.yugiohcardguide.com', text: 'Yu-Gi-Oh! Card Guide', color: '#1A237E', description: 'Comprehensive guide to Yu-Gi-Oh! cards, strategies, and decks.' },
{ url: 'https://trends.google.com', text: 'Google Trends', color: '#4285F4', description: 'Google tool for exploring search trends and popular topics worldwide.' },
{ url: 'https://www.apple.com/', text: 'Apple', color: '#A2AAAD', description: 'Technology company specializing in consumer electronics.' },
{ url: 'https://www.imdb.com/', text: 'IMDb', color: '#F5C518', description: 'Online database for movies, TV shows, and celebrity info.' },
{ url: 'https://www.cnn.com/', text: 'CNN', color: '#CC0000', description: 'News platform providing 24-hour global news coverage.' },
{ url: 'https://www.etsy.com/', text: 'Etsy', color: '#F16521', description: 'Online marketplace for handmade, vintage, and creative goods.' },
{ url: 'https://www.quora.com/', text: 'Quora', color: '#B92B27', description: 'Platform to ask questions and share knowledge.' },
{ url: 'https://www.dropbox.com/', text: 'Dropbox', color: '#007EE5', description: 'Cloud storage service for file sharing and collaboration.' },
{ url: 'https://www.salesforce.com/', text: 'Salesforce', color: '#00A1E0', description: 'Customer relationship management (CRM) platform.' },
{ url: 'https://www.adobe.com/', text: 'Adobe', color: '#FF0000', description: 'Software company known for creative applications like Photoshop.' },
{ url: 'https://www.stackoverflow.com/', text: 'Stack Overflow', color: '#F48024', description: 'Q&A platform for programmers and developers.' },
{ url: 'https://www.airbnb.com/', text: 'Airbnb', color: '#FF5A5F', description: 'Platform for renting short-term lodging and experiences.' },
{ url: 'https://www.uber.com/', text: 'Uber', color: '#000000', description: 'Ride-hailing service for transportation and delivery.' },
{ url: 'https://www.alibaba.com/', text: 'Alibaba', color: '#FF6A00', description: 'Global marketplace connecting buyers and suppliers.' },
{ url: 'https://www.tiktok.com/', text: 'TikTok', color: '#000000', description: 'Platform for creating and sharing short-form mobile videos.' },
{ url: 'https://www.slack.com/', text: 'Slack', color: '#4A154B', description: 'Team communication and collaboration platform.' },
{ url: 'https://www.nytimes.com/', text: 'The New York Times', color: '#000000', description: 'Leading American newspaper offering global news and analysis.' },
{ url: 'https://www.theguardian.com/', text: 'The Guardian', color: '#005689', description: 'British newspaper offering news and opinion pieces.' },
{ url: 'https://www.reuters.com/', text: 'Reuters', color: '#FF8000', description: 'International news agency providing real-time news and reports.' },
{ url: 'https://www.washingtonpost.com/', text: 'The Washington Post', color: '#231F20', description: 'Major American newspaper focused on national politics.' },
{ url: 'https://www.bbc.com/news', text: 'BBC News', color: '#BB1919', description: 'British news organization providing global news coverage.' },
{ url: 'https://www.zillow.com/', text: 'Zillow', color: '#0074E4', description: 'Real estate platform for buying, selling, and renting homes.' },

{ url: 'https://www.nike.com/', text: 'Nike', color: '#111111', description: 'Global brand known for athletic footwear, apparel, and equipment.' },
{ url: 'https://www.target.com/', text: 'Target', color: '#CC0000', description: 'American retail company offering a variety of products.' },
{ url: 'https://www.costco.com/', text: 'Costco', color: '#B3121E', description: 'Membership-based warehouse club for bulk goods.' },
{ url: 'https://www.walmart.com/', text: 'Walmart', color: '#0071CE', description: 'Largest American retailer offering groceries and other goods.' },
{ url: 'https://www.homeadvisor.com/', text: 'HomeAdvisor', color: '#00AACC', description: 'Platform connecting homeowners with local service professionals.' },
{ url: 'https://www.expedia.com/', text: 'Expedia', color: '#00355F', description: 'Online travel booking platform for flights, hotels, and cars.' },
{ url: 'https://www.craigslist.org/', text: 'Craigslist', color: '#660099', description: 'Classified ads website for jobs, housing, services, and more.' },
{ url: 'https://www.nasa.gov/', text: 'NASA', color: '#0B3D91', description: 'The United States government’s space agency.' },
{ url: 'https://www.espn.com/', text: 'ESPN', color: '#D51D2D', description: 'Global sports network providing news, scores, and live events.' },
{ url: 'https://www.hulu.com/', text: 'Hulu', color: '#3DBB3D', description: 'Streaming service offering TV shows, movies, and originals.' },
{ url: 'https://www.netflix.com/', text: 'Netflix', color: '#E50914', description: 'Streaming service offering movies, TV shows, and documentaries.' },
{ url: 'https://www.bbc.com/', text: 'BBC', color: '#BB1919', description: 'British Broadcasting Corporation providing global news and media content.' },
{ url: 'https://www.nationalgeographic.com/', text: 'National Geographic', color: '#FFCC00', description: 'Popular science, geography, and history magazine.' },
{ url: 'https://www.forbes.com/', text: 'Forbes', color: '#BC1F3D', description: 'Global media company focusing on business, investing, technology, and leadership.' },
{ url: 'https://www.time.com/', text: 'TIME', color: '#B9071D', description: 'American news magazine covering politics, health, and current events.' },
{ url: 'https://www.theverge.com/', text: 'The Verge', color: '#1A1A1A', description: 'News and media platform focusing on technology, science, and culture.' },
{ url: 'https://www.tesla.com/', text: 'Tesla', color: '#CC0000', description: 'Electric car manufacturer and energy company.' },
{ url: 'https://www.discord.com/', text: 'Discord', color: '#5865F2', description: 'Communication platform primarily for gaming communities.' },
{ url: 'https://www.spotify.com/', text: 'Spotify', color: '#1DB954', description: 'Music streaming service offering millions of songs and podcasts.' },
{ url: 'https://www.paypal.com/', text: 'PayPal', color: '#003087', description: 'Online payment processing service for businesses and individuals.' },
{ url: 'https://www.weibo.com/', text: 'Weibo', color: '#E6162D', description: 'Chinese social media platform, similar to Twitter.' },
{ url: 'https://www.qq.com/', text: 'QQ', color: '#12B7F5', description: 'Popular Chinese messaging, social media, and web portal.' },
{ url: 'https://www.taobao.com/', text: 'Taobao', color: '#FF5000', description: 'Chinese online shopping platform owned by Alibaba.' },
{ url: 'https://www.tmall.com/', text: 'Tmall', color: '#C80000', description: 'B2C online retail platform operated by Alibaba.' },
{ url: 'https://www.sina.com.cn/', text: 'Sina', color: '#FF5733', description: 'Chinese news portal and social media platform.' },
{ url: 'https://www.yelp.com/', text: 'Yelp', color: '#AF0606', description: 'Platform for user-generated reviews of local businesses.' },
{ url: 'https://www.zomato.com/', text: 'Zomato', color: '#E23744', description: 'Restaurant discovery and food delivery platform.' },
{ url: 'https://www.priceline.com/', text: 'Priceline', color: '#003DA5', description: 'Online travel booking platform for flights, hotels, and cars.' },
{ url: 'https://www.tripadvisor.com/', text: 'Tripadvisor', color: '#34E0A1', description: 'Travel platform for reviews and booking hotels, flights, and activities.' },
{ url: 'https://www.cheaptickets.com/', text: 'CheapTickets', color: '#000000', description: 'Online travel agency offering discounts on flights, hotels, and rentals.' },
{ url: 'https://www.delta.com/', text: 'Delta', color: '#E81932', description: 'Major American airline offering global flight services.' },
{ url: 'https://www.united.com/', text: 'United Airlines', color: '#003366', description: 'Major American airline providing domestic and international flights.' },
{ url: 'https://www.americanexpress.com/', text: 'American Express', color: '#2E77BC', description: 'Financial services corporation known for credit cards and travel services.' },
{ url: 'https://www.mastercard.com/', text: 'Mastercard', color: '#EB001B', description: 'Global financial services company specializing in credit cards.' },
{ url: 'https://www.visa.com/', text: 'Visa', color: '#1A1F71', description: 'Global payments technology company known for credit and debit cards.' },
{ url: 'https://www.chase.com/', text: 'Chase', color: '#007EBF', description: 'American bank offering financial services and credit cards.' },
{ url: 'https://www.wellsfargo.com/', text: 'Wells Fargo', color: '#FF4F00', description: 'American bank providing banking, loans, and investment services.' },
{ url: 'https://www.bankofamerica.com/', text: 'Bank of America', color: '#D32F2F', description: 'Major American bank offering consumer financial services.' },
{ url: 'https://www.goldmansachs.com/', text: 'Goldman Sachs', color: '#333333', description: 'Investment bank and financial services company.' },
{ url: 'https://www.jpmorganchase.com/', text: 'JPMorgan Chase', color: '#1E4B75', description: 'Global investment bank and financial services provider.' },
{ url: 'https://www.morganstanley.com/', text: 'Morgan Stanley', color: '#0072CE', description: 'Global financial services firm specializing in investment banking and wealth management.' },
{ url: 'https://www.citigroup.com/', text: 'Citigroup', color: '#1A6CB2', description: 'Global bank offering financial services.' },
{ url: 'https://www.bloomberg.com/', text: 'Bloomberg', color: '#000000', description: 'Global financial, economic, and business news platform.' },
{ url: 'https://www.cnbc.com/', text: 'CNBC', color: '#2D72D9', description: 'Business news and real-time financial market coverage.' },
{ url: 'https://www.wsj.com/', text: 'The Wall Street Journal', color: '#2C2C2C', description: 'Leading American business-focused newspaper.' },
{ url: 'https://www.ft.com/', text: 'Financial Times', color: '#FF6F00', description: 'International daily newspaper focused on financial news and markets.' },
{ url: 'https://www.businessinsider.com/', text: 'Business Insider', color: '#0055A5', description: 'News website providing business, tech, and financial insights.' },

{ url: 'https://www.adidas.com/', text: 'Adidas', color: '#000000', description: 'Sportswear company producing shoes, clothing, and accessories.' },
{ url: 'https://www.puma.com/', text: 'Puma', color: '#000000', description: 'Sports brand offering footwear, apparel, and accessories.' },
{ url: 'https://www.samsung.com/', text: 'Samsung', color: '#1428A0', description: 'Multinational electronics company known for smartphones, TVs, and appliances.' },
{ url: 'https://www.lg.com/', text: 'LG', color: '#A50034', description: 'Global electronics company producing home appliances, TVs, and mobile devices.' },
{ url: 'https://www.sony.com/', text: 'Sony', color: '#000000', description: 'Multinational company specializing in electronics, gaming, and entertainment.' },
{ url: 'https://www.xiaomi.com/', text: 'Xiaomi', color: '#FF6900', description: 'Chinese electronics company producing smartphones and other consumer electronics.' },
{ url: 'https://www.oneplus.com/', text: 'OnePlus', color: '#F5010C', description: 'Smartphone manufacturer known for high-quality, affordable phones.' },
{ url: 'https://www.oppo.com/', text: 'Oppo', color: '#00B348', description: 'Chinese consumer electronics and mobile communications company.' },
{ url: 'https://www.vivo.com/', text: 'Vivo', color: '#33A0FF', description: 'Chinese technology company producing smartphones and accessories.' },
{ url: 'https://www.realme.com/', text: 'Realme', color: '#FEC107', description: 'Chinese smartphone manufacturer offering affordable mobile devices.' },
{ url: 'https://www.huawei.com/', text: 'Huawei', color: '#C9000F', description: 'Chinese multinational technology company focused on telecommunications.' },
{ url: 'https://www.lenovo.com/', text: 'Lenovo', color: '#E2231A', description: 'Global technology company specializing in laptops and electronics.' },
{ url: 'https://www.hp.com/', text: 'HP', color: '#0096D6', description: 'American technology company known for laptops, printers, and accessories.' },
{ url: 'https://www.dell.com/', text: 'Dell', color: '#007DB8', description: 'Technology company specializing in computers, laptops, and accessories.' },
{ url: 'https://www.asus.com/', text: 'ASUS', color: '#002942', description: 'Technology company known for laptops, motherboards, and peripherals.' },
{ url: 'https://www.acer.com/', text: 'Acer', color: '#83B81A', description: 'Electronics company producing laptops, monitors, and accessories.' },
{ url: 'https://www.msi.com/', text: 'MSI', color: '#CC0000', description: 'Taiwanese electronics company specializing in gaming laptops and hardware.' },
{ url: 'https://www.razer.com/', text: 'Razer', color: '#00FF00', description: 'Gaming hardware company known for laptops, peripherals, and accessories.' },
{ url: 'https://www.nintendo.com/', text: 'Nintendo', color: '#E60012', description: 'Japanese video game company known for popular franchises and consoles.' },
{ url: 'https://www.playstation.com/', text: 'PlayStation', color: '#003791', description: 'Gaming brand owned by Sony, producing consoles and exclusive games.' },
{ url: 'https://www.xbox.com/', text: 'Xbox', color: '#107C10', description: 'Gaming brand owned by Microsoft, known for consoles and games.' },
{ url: 'https://www.steampowered.com/', text: 'Steam', color: '#171A21', description: 'Digital distribution platform for video games and software.' },
{ url: 'https://www.epicgames.com/', text: 'Epic Games', color: '#313131', description: 'Video game and software developer known for Fortnite and Unreal Engine.' },
{ url: 'https://www.riotgames.com/', text: 'Riot Games', color: '#D32936', description: 'Video game developer known for League of Legends and Valorant.' },
{ url: 'https://www.activision.com/', text: 'Activision', color: '#333333', description: 'American video game publisher behind Call of Duty and other titles.' },
{ url: 'https://www.ea.com/', text: 'Electronic Arts', color: '#000000', description: 'American video game company known for EA Sports and other franchises.' },
{ url: 'https://www.ubisoft.com/', text: 'Ubisoft', color: '#000000', description: 'French video game developer known for Assassin’s Creed and other titles.' },
{ url: 'https://www.snapchat.com/', text: 'Snapchat', color: '#FFFC00', description: 'Photo messaging app known for temporary content and filters.' },
{ url: 'https://www.pinterest.com/', text: 'Pinterest', color: '#E60023', description: 'Image-sharing platform to discover ideas and inspirations.' },
{ url: 'https://www.reddit.com/', text: 'Reddit', color: '#FF4500', description: 'Community platform for discussions and content sharing.' },
{ url: 'https://www.flickr.com/', text: 'Flickr', color: '#0063DC', description: 'Photo-sharing platform popular among photographers and artists.' },
{ url: 'https://www.deviantart.com/', text: 'DeviantArt', color: '#05CC47', description: 'Online community for artists and art lovers to share and discuss artwork.' },
{ url: 'https://www.tumblr.com/', text: 'Tumblr', color: '#36465D', description: 'Microblogging platform for sharing text, photos, and other content.' },
{ url: 'https://www.vimeo.com/', text: 'Vimeo', color: '#162221', description: 'Video-sharing platform for creators and professionals.' },
{ url: 'https://www.dailymotion.com/', text: 'Dailymotion', color: '#0066DC', description: 'Video-sharing platform offering various types of content.' },
{ url: 'https://www.soundcloud.com/', text: 'SoundCloud', color: '#FF5500', description: 'Platform for streaming and sharing music and podcasts.' },
{ url: 'https://www.audible.com/', text: 'Audible', color: '#F8991C', description: 'Audiobook and spoken-word entertainment platform owned by Amazon.' },
{ url: 'https://www.shazam.com/', text: 'Shazam', color: '#1F8ECE', description: 'Music identification service helping users recognize songs.' },
{ url: 'https://www.pandora.com/', text: 'Pandora', color: '#005483', description: 'Music streaming and recommendation service.' },
{ url: 'https://www.iheart.com/', text: 'iHeartRadio', color: '#C60000', description: 'Radio network offering live and on-demand music, podcasts, and shows.' },
{ url: 'https://www.deezer.com/', text: 'Deezer', color: '#FF2900', description: 'Music streaming service offering playlists and podcasts.' },
{ url: 'https://www.linkedin.com/', text: 'LinkedIn', color: '#0077B5', description: 'Professional networking platform for job seekers and employers.' },
{ url: 'https://www.glassdoor.com/', text: 'Glassdoor', color: '#0C4A7D', description: 'Platform for job listings, company reviews, and salary insights.' },
{ url: 'https://www.monster.com/', text: 'Monster', color: '#6F41A3', description: 'Global employment platform for job seekers and employers.' },
{ url: 'https://www.indeed.com/', text: 'Indeed', color: '#003A9B', description: 'Job search engine for job listings from various industries.' },
{ url: 'https://www.ziprecruiter.com/', text: 'ZipRecruiter', color: '#33C474', description: 'Online platform for employers to post jobs and find candidates.' },
{ url: 'https://www.careerbuilder.com/', text: 'CareerBuilder', color: '#004179', description: 'Job search engine connecting employers and job seekers.' },
{ url: 'https://www.lyft.com/', text: 'Lyft', color: '#FF00BF', description: 'Ride-sharing service providing transportation solutions.' },
{ url: 'https://www.booking.com/', text: 'Booking.com', color: '#003580', description: 'Online travel platform for booking hotels, flights, and accommodations.' },
{ url: 'https://www.trivago.com/', text: 'Trivago', color: '#009688', description: 'Hotel comparison and booking platform.' },
{ url: 'https://www.kayak.com/', text: 'Kayak', color: '#00B2A9', description: 'Travel search engine for comparing flight, hotel, and car rental prices.' },
{ url: 'https://www.cheapflights.com/', text: 'CheapFlights', color: '#FF5F5F', description: 'Search engine for finding cheap flight deals and offers.' },
{ url: 'https://www.southwest.com/', text: 'Southwest Airlines', color: '#F8C500', description: 'American low-cost airline known for budget-friendly flights.' },
{ url: 'https://www.alaskaair.com/', text: 'Alaska Airlines', color: '#002B5C', description: 'Major American airline offering flights across the United States and to international destinations.' },
{ url: 'https://www.jetblue.com/', text: 'JetBlue', color: '#0039A6', description: 'American airline known for its budget-friendly flights and customer service.' },
{ url: 'https://www.spirit.com/', text: 'Spirit Airlines', color: '#F7D700', description: 'Low-cost American airline providing budget travel options.' },
{ url: 'https://www.frontierairlines.com/', text: 'Frontier Airlines', color: '#008E2F', description: 'Low-cost airline offering domestic and international flights.' },
{ url: 'https://www.wyndhamhotels.com/', text: 'Wyndham Hotels', color: '#2D3A3A', description: 'Hotel chain offering a range of lodging options around the world.' },
{ url: 'https://www.marriott.com/', text: 'Marriott', color: '#D4AF37', description: 'Global hotel chain providing luxury and budget accommodations.' },
{ url: 'https://www.hilton.com/', text: 'Hilton', color: '#002A5E', description: 'International hotel chain offering a variety of accommodation options.' },
{ url: 'https://www.hyatt.com/', text: 'Hyatt', color: '#003C71', description: 'Global hotel chain with a range of lodging options from luxury to budget.' },
{ url: 'https://www.intercontinental.com/', text: 'InterContinental', color: '#003399', description: 'Luxury hotel brand known for its global locations.' },
{ url: 'https://www.ritz-carlton.com/', text: 'Ritz-Carlton', color: '#C6A657', description: 'Luxury hotel and resort chain known for high-end accommodations.' },
{ url: 'https://www.fairmont.com/', text: 'Fairmont', color: '#CCB752', description: 'Luxury hotel brand with properties around the world.' },
{ url: 'https://www.banyantree.com/', text: 'Banyan Tree', color: '#006C4C', description: 'Luxury resort brand offering high-end accommodations and spa services.' },
{ url: 'https://www.shangri-la.com/', text: 'Shangri-La', color: '#BF8C3C', description: 'Luxury hotel chain with properties in major cities worldwide.' },
{ url: 'https://www.mandarinoriental.com/', text: 'Mandarin Oriental', color: '#CC8C4F', description: 'Luxury hotel group offering premium accommodations and services.' },
{ url: 'https://www.thomsonreuters.com/', text: 'Thomson Reuters', color: '#0073B8', description: 'Global information and media company providing professional and financial information.' },
{ url: 'https://www.fedex.com/', text: 'FedEx', color: '#FF6600', description: 'Courier delivery services company offering shipping and logistics solutions.' },
{ url: 'https://www.dhl.com/', text: 'DHL', color: '#FFCC00', description: 'International courier company providing express mail and logistics services.' },
{ url: 'https://www.ups.com/', text: 'UPS', color: '#3E3A39', description: 'Package delivery and supply chain management company.' },
{ url: 'https://www.tnt.com/', text: 'TNT', color: '#FF6600', description: 'International courier company providing express and freight services.' },
{ url: 'https://www.usps.com/', text: 'USPS', color: '#004B87', description: 'United States Postal Service providing mail and delivery services.' },

{ url: 'https://www.kroger.com/', text: 'Kroger', color: '#004B49', description: 'Supermarket chain providing groceries, pharmacy, and other retail products.' },
{ url: 'https://pisn.kemdikbud.go.id', text: 'PISN Kemdikbud', color: '#FF6F00', description: 'Pangkalan Informasi dan Seleksi Nasional (PISN) Kemdikbud untuk akses informasi terkait pendidikan tinggi.' },
{ url: 'https://pddikti.kemdikbud.go.id', text: 'PDDikti', color: '#00796B', description: 'Pangkalan Data Pendidikan Tinggi yang menyediakan informasi resmi terkait perguruan tinggi di Indonesia.' },
{ url: 'https://merdekabelajar.kemdikbud.go.id', text: 'Merdeka Belajar', color: '#4CAF50', description: 'Program pendidikan dari Kemdikbud yang bertujuan untuk memberikan kebebasan dan fleksibilitas dalam belajar.' },
{ url: 'https://create.kahoot.it/discover', text: 'Kahoot Discover', color: '#FFDD00', description: 'Platform interaktif untuk membuat, berbagi, dan memainkan kuis edukatif serta aktivitas belajar interaktif.' },
{ url: 'https://www.terabox.com/main?category=all', text: 'TeraBox', color: '#00C3FF', description: 'Layanan penyimpanan cloud yang aman dan andal, menyediakan ruang besar untuk file digital Anda.' },
{ url: 'https://mega.nz/chat', text: 'Mega Chat', color: '#FF0000', description: 'Platform penyimpanan cloud terenkripsi dengan fitur chat yang aman dan privasi terjamin.' },
{ "url": "https://kompas.id", "text": "Kompas", "color": "#1E88E5", "description": "Portal berita terkemuka di Indonesia yang menyediakan berita terkini dan terpercaya." },
{ "url": "https://detik.id", "text": "Detik", "color": "#FF5722", "description": "Sumber berita terupdate dan terhangat di Indonesia." },
{ "url": "https://liputan6.com", "text": "Liputan 6", "color": "#FFC107", "description": "Berita terbaru dari berbagai topik, termasuk politik, bisnis, dan hiburan." },
{ "url": "https://tirto.id", "text": "Tirto", "color": "#4CAF50", "description": "Media online yang menyajikan berita dan informasi mendalam dengan pendekatan analitis." },
{ "url": "https://tempo.co", "text": "Tempo", "color": "#F57F17", "description": "Media berita dengan fokus pada jurnalisme investigasi dan berita berkualitas." },
{ "url": "https://cnnindonesia.com", "text": "CNN Indonesia", "color": "#FF6F00", "description": "Versi Indonesia dari CNN, menyediakan berita lokal dan internasional." },
{ "url": "https://republika.co.id", "text": "Republika", "color": "#E53935", "description": "Berita dan informasi dari perspektif Islam dan perspektif lokal Indonesia." },
{ "url": "https://metro.tv", "text": "Metro TV", "color": "#1976D2", "description": "Saluran berita televisi yang juga menyediakan berita online dan video terbaru." },
{ "url": "https://indonesia.id", "text": "Indonesia ID", "color": "#0288D1", "description": "Portal informasi dan berita tentang berbagai aspek kehidupan di Indonesia." },
{ "url": "https://kumparan.com", "text": "Kumparan", "color": "#7B1FA2", "description": "Platform berita dan media sosial yang menyajikan berita terkini dan topik menarik." },
{ "url": "https://viva.co.id", "text": "Viva", "color": "#FF4081", "description": "Situs berita dan hiburan dengan berbagai konten menarik dan terkini." },
{ "url": "https://jakartapost.com", "text": "Jakarta Post", "color": "#F57C00", "description": "Media berita berbahasa Inggris yang menyediakan informasi dan berita terkini dari Indonesia." },
{ "url": "https://suara.com", "text": "Suara", "color": "#8E24AA", "description": "Portal berita dengan berbagai topik terkini dan informasi penting dari seluruh Indonesia." },
{ "url": "https://sindonews.com", "text": "Sindo News", "color": "#D32F2F", "description": "Portal berita yang menyediakan berita terbaru dan informasi dari berbagai sektor." },
{ "url": "https://pajak.go.id", "text": "Pajak", "color": "#0D47A1", "description": "Situs resmi Direktorat Jenderal Pajak Indonesia untuk informasi perpajakan." },
{ "url": "https://bankmandiri.co.id", "text": "Bank Mandiri", "color": "#0D47A1", "description": "Situs resmi Bank Mandiri yang menyediakan layanan perbankan dan informasi finansial." },
{ "url": "https://bca.co.id", "text": "BCA", "color": "#004D40", "description": "Situs resmi Bank Central Asia untuk layanan perbankan dan informasi terkait." },
{ "url": "https://bukalapak.com", "text": "Bukalapak", "color": "#FF5722", "description": "Platform e-commerce terbesar di Indonesia untuk membeli dan menjual berbagai produk." },
{ "url": "https://tokopedia.com", "text": "Tokopedia", "color": "#1E88E5", "description": "Situs e-commerce yang menyediakan berbagai produk dari berbagai kategori." },
{ "url": "https://shopee.co.id", "text": "Shopee", "color": "#FF6F00", "description": "Platform belanja online yang menawarkan berbagai produk dengan harga kompetitif." },
{ "url": "https://traveloka.com", "text": "Traveloka", "color": "#8E24AA", "description": "Situs pemesanan tiket pesawat, hotel, dan layanan perjalanan lainnya." },
{ "url": "https://gojek.com", "text": "Gojek", "color": "#00BFAE", "description": "Platform layanan on-demand termasuk transportasi, makanan, dan pengiriman barang." },
{ "url": "https://grab.com", "text": "Grab", "color": "#00C853", "description": "Layanan transportasi, pengiriman makanan, dan layanan on-demand lainnya." },
{ "url": "https://bri.co.id", "text": "Bank BRI", "color": "#C2185B", "description": "Situs resmi Bank Rakyat Indonesia dengan berbagai layanan perbankan." },
{ "url": "https://unilever.co.id", "text": "Unilever", "color": "#FFEB3B", "description": "Situs resmi Unilever Indonesia yang menyediakan informasi produk dan berita perusahaan." },
{ "url": "https://indocement.co.id", "text": "Indocement", "color": "#B71C1C", "description": "Situs resmi produsen semen terkemuka di Indonesia." },
{ "url": "https://pertamina.com", "text": "Pertamina", "color": "#FF6F00", "description": "Situs resmi PT Pertamina untuk informasi tentang energi dan produk minyak." },
{ "url": "https://telkom.co.id", "text": "Telkom", "color": "#3F51B5", "description": "Situs resmi PT Telekomunikasi Indonesia untuk layanan telekomunikasi dan internet." },
{ "url": "https://xl.co.id", "text": "XL Axiata", "color": "#FF5722", "description": "Situs resmi XL Axiata untuk informasi layanan telekomunikasi dan data." },
{ "url": "https://axis.co.id", "text": "Axis", "color": "#009688", "description": "Situs resmi Axis untuk layanan komunikasi dan internet di Indonesia." },
{ "url": "https://smartfren.com", "text": "Smartfren", "color": "#FF5722", "description": "Situs resmi Smartfren untuk layanan internet dan telekomunikasi." },
{ "url": "https://app.coderabbit.ai/login", "text": "Code Rabbit", "color": "#2E7D32", "description": "Platform pembelajaran coding interaktif yang membantu pengguna belajar pemrograman." },
{ "url": "https://archive.org/", "text": "Archive.org", "color": "#4CAF50", "description": "Perpustakaan digital yang menyediakan akses ke buku, film, musik, dan situs web yang telah diarsipkan." },
{ "url": "https://app.box.com/folder/0", "text": "Box", "color": "#2962FF", "description": "Platform penyimpanan cloud yang memungkinkan pengguna untuk menyimpan dan berbagi file secara aman." },
{ "url": "https://www.wikipedia.org/", "text": "Wikipedia", "color": "#F44336", "description": "Ensiklopedia online yang bebas diakses dan kolaboratif dengan berbagai topik dari seluruh dunia." },
{ "url": "https://sinta.kemdikbud.go.id/scopus", "text": "SINTA Scopus", "color": "#00796B", "description": "Portal integrasi data publikasi ilmiah dari Indonesia yang terindeks di Scopus." },
{ "url": "https://scholar.google.com/", "text": "Google Scholar", "color": "#F57F17", "description": "Mesin pencari literatur ilmiah yang mencakup artikel, tesis, buku, dan jurnal akademik." },
{ "url": "https://garuda.kemdikbud.go.id/journal", "text": "Garuda Journal", "color": "#3F51B5", "description": "Portal yang menyediakan akses ke berbagai jurnal ilmiah yang diterbitkan di Indonesia." },
{ "url": "https://www.codingnepalweb.com/", "text": "Coding Nepal", "color": "#1E88E5", "description": "Situs tutorial pemrograman web yang menyediakan berbagai panduan dan contoh proyek." },
{ "url": "https://belajarmikrotik.com/mtcna/", "text": "Belajar Mikrotik MTCNA", "color": "#F57C00", "description": "Platform pembelajaran sertifikasi MTCNA untuk memahami jaringan Mikrotik." },
{ "url": "https://www.arduino.cc/", "text": "Arduino", "color": "#009688", "description": "Situs resmi Arduino yang menyediakan hardware open-source dan komunitas pembuat proyek elektronik." },
{ "url": "https://www.webtoons.com/id", "text": "Webtoons", "color": "#FF5722", "description": "Platform populer untuk membaca webtoon dan komik dari berbagai genre dan negara." },
{ "url": "https://versus.com/id", "text": "Versus", "color": "#4CAF50", "description": "Situs perbandingan yang membantu pengguna membandingkan produk, gadget, dan layanan dengan mudah." },
{ "url": "https://lahelu.com/", "text": "Lahelu", "color": "#7B1FA2", "description": "Situs yang menyediakan artikel dan informasi terkini tentang teknologi dan produk gadget." },
{ "url": "https://www.gsmarena.com/", "text": "GSMArena", "color": "#FF4081", "description": "Portal informasi terkemuka untuk spesifikasi dan review gadget dan ponsel terbaru." },
{ "url": "https://fastpedia.io/", "text": "Fastpedia", "color": "#1E88E5", "description": "Situs informasi cepat yang menyediakan beragam topik dalam bentuk ringkas dan mudah dipahami." },
{ "url": "https://www.npmjs.com/", "text": "NPM", "color": "#FF5722", "description": "Repository JavaScript terbesar yang menyediakan ribuan paket untuk pengembangan aplikasi." },
{ "url": "https://www.bps.go.id/", "text": "BPS", "color": "#4CAF50", "description": "Badan Pusat Statistik Indonesia yang menyediakan data statistik dan informasi penting negara." },
{ "url": "https://www.gns3.com/", "text": "GNS3", "color": "#009688", "description": "Simulator jaringan untuk membangun, mendesain, dan menguji jaringan secara virtual." },
{ "url": "https://openui.fly.dev/ai/new", "text": "OpenUI AI", "color": "#FF4081", "description": "Situs yang menyediakan antarmuka AI terbuka untuk memudahkan eksperimen dan pengembangan AI." },
{ "url": "https://www.cymath.com/", "text": "Cymath", "color": "#F57C00", "description": "Situs solver matematika online yang menyediakan solusi dengan langkah-langkah untuk berbagai jenis soal matematika." },
{ "url": "https://www.eve-ng.net/", "text": "EVE-NG", "color": "#7B1FA2", "description": "Emulator jaringan profesional untuk menciptakan dan mengelola lab jaringan secara virtual." },
{ "url": "https://app.notta.ai/", "text": "Notta", "color": "#00BFAE", "description": "Alat transkripsi AI yang mengubah audio menjadi teks dengan cepat dan akurat." },
{ "url": "https://goodtape.io/", "text": "GoodTape", "color": "#F57F17", "description": "Alat perekaman dan wawancara berbasis AI yang membantu pengguna menghasilkan rekaman berkualitas tinggi." },
{ url: 'https://overthewire.org/wargames/', text: 'OverTheWire Wargames', color: '#4B4B4B', description: 'A series of games to learn and practice security concepts in a fun way.' },
{ url: 'https://www.humata.ai/', text: 'Humata AI', color: '#6200EA', description: 'AI tool to instantly analyze documents, providing insights and summaries.' },
{ url: 'https://quickref.me/', text: 'QuickRef', color: '#FF7043', description: 'Quick reference guides for developers, with code snippets and cheat sheets.' },
{ url: 'https://draft.blogger.com/dashboard/reading?bpli=1&pli=1', text: 'Blogger Dashboard', color: '#F57C00', description: 'Dashboard for managing your Blogger blogs and reading lists.' },
{ url: 'https://www.open.edu/openlearn/', text: 'OpenLearn', color: '#0057A6', description: 'Free online courses from the Open University, covering various subjects.' },
{ url: 'https://mulfu.co/', text: 'Mulfu', color: '#FF8A80', description: 'AI-powered platform for generating personalized videos with ease.' },
{ url: 'https://ptable.com', text: 'Ptable', color: '#1E88E5', description: 'Interactive periodic table providing detailed element information, properties, and visualizations.' },
{ url: 'https://gizmos.explorelearning.com/', text: 'Gizmos', color: '#FFC107', description: 'Interactive math and science simulations for teaching various concepts.' },
{ url: 'https://phet.colorado.edu/', text: 'PhET', color: '#4CAF50', description: 'Free interactive math and science simulations for students and educators.' },
{ url: 'https://www.sciencejournalforkids.org/', text: 'Science Journal for Kids', color: '#FF5722', description: 'Scientific articles rewritten for kids to understand and learn about the latest research.' },
{ url: 'https://www.desmos.com/', text: 'Desmos', color: '#9C27B0', description: 'Graphing calculator and math learning tool used to visualize functions and solve math problems.' },
{ url: 'https://www.knowledgehook.com/', text: 'Knowledgehook', color: '#E91E63', description: 'Math education platform that offers learning assessments and tools for teachers and students.' },
{ url: 'https://saweria.co/register', text: 'Saweria', color: '#FFB74D', description: 'Platform untuk konten kreator menerima dukungan finansial dari penggemar melalui donasi.' },
{ url: 'https://app.logodiffusion.com/gen/image-workspace', text: 'LogoDiffusion', color: '#42A5F5', description: 'AI-powered platform for generating high-quality logos and images.' },
{ url: 'https://gptgo.ai/id', text: 'GPTGo AI', color: '#66BB6A', description: 'AI-based tool that provides language generation services in Bahasa Indonesia.' },
{ url: 'https://id.khanacademy.org', text: 'Khan Academy Indonesia', color: '#FF7043', description: 'Platform belajar gratis untuk siswa dengan materi edukasi dari berbagai bidang.' },
{ url: 'https://answerai.pro/', text: 'AnswerAI', color: '#AB47BC', description: 'AI tool designed to answer questions based on large datasets or documents.' },
{ url: 'https://toolfinder.co/', text: 'ToolFinder', color: '#78909C', description: 'Platform to discover AI tools and applications across multiple categories.' },
{ url: 'https://trello.com/create-first-team', text: 'Trello', color: '#29B6F6', description: 'Popular project management tool to organize tasks and collaborate with teams efficiently.' },
{ url: 'https://app.writesonic.com/', text: 'Writesonic', color: '#FF5252', description: 'AI-powered writing tool for creating content like articles, ads, and social media posts.' },
{ url: 'https://www.typelit.io/', text: 'TypeLit.io', color: '#7E57C2', description: 'Typing practice platform using famous literary works to improve typing skills.' },
{ url: 'https://www.croxyproxy.com/_id/', text: 'CroxyProxy', color: '#4CAF50', description: 'Proxy online gratis untuk mengakses situs web dengan aman dan anonim.' },
{ url: 'https://www.proxysite.com/', text: 'ProxySite', color: '#2196F3', description: 'Proxy web yang memungkinkan pengguna mengakses situs yang diblokir dengan aman.' },
{ url: 'https://zty.pe/', text: 'Ztype', color: '#FF5722', description: 'Game mengetik sambil menembak musuh. Bantu meningkatkan kecepatan mengetik.' },
{ url: 'https://uiball.com/', text: 'UI Ball', color: '#673AB7', description: 'Sumber animasi dan ikon loading yang dapat diunduh untuk proyek UI.' },
{ url: 'https://tinywow.com/', text: 'TinyWow', color: '#009688', description: 'Alat online gratis untuk mengonversi file, mengedit gambar, dan lainnya.' },
{ url: 'https://sketch.metademolab.com/', text: 'Sketch by Meta', color: '#03A9F4', description: 'Alat AI untuk membuat sketsa secara interaktif dan bereksperimen dengan desain.' },
{ url: 'https://www.framer.com/', text: 'Framer', color: '#E91E63', description: 'Alat desain interaktif untuk membuat prototipe web yang responsif.' },
{ url: 'http://radio.garden/', text: 'Radio Garden', color: '#4CAF50', description: 'Jelajahi stasiun radio di seluruh dunia melalui antarmuka interaktif berbasis peta.' },
{ url: 'https://coefont.cloud/', text: 'Coefont', color: '#FF9800', description: 'Layanan text-to-speech untuk membuat suara AI yang dapat disesuaikan.' },
{ url: 'https://theresanaiforthat.com/', text: 'There\'s an AI for That', color: '#795548', description: 'Database yang mencakup berbagai aplikasi AI untuk berbagai kebutuhan.' },
{ url: 'https://sketchfab.com/', text: 'Sketchfab', color: '#2196F3', description: 'Platform untuk berbagi dan menjelajahi model 3D interaktif.' },
{ url: 'https://appsgeyser.com/', text: 'AppsGeyser', color: '#9C27B0', description: 'Alat pembuat aplikasi Android gratis tanpa perlu pengkodean.' },
{ url: 'https://thecrashcourse.com/', text: 'CrashCourse', color: '#F44336', description: 'Kursus video pendidikan dengan berbagai topik mulai dari sejarah hingga sains.' },
{ url: 'https://wokwi.com/', text: 'Wokwi', color: '#607D8B', description: 'Simulator online untuk Arduino, ESP32, dan berbagai proyek elektronika.' },


];
